# Generated by Django 3.2.6 on 2022-01-22 13:51

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('available_at', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None, verbose_name='Available at')),
                ('interval', models.PositiveSmallIntegerField(choices=[(15, '15 Minutes'), (30, '30 Minutes'), (45, '45 Minutes')], default=30, verbose_name='Interval')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='Host')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
