# Generated by Django 3.2.6 on 2022-01-23 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('interval', models.PositiveSmallIntegerField(choices=[(15, '15 Minutes'), (30, '30 Minutes'), (45, '45 Minutes')], default=30, verbose_name='Interval')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='Host')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('available_at', models.DateTimeField(verbose_name='Available at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='Reserved ?')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='meetings.meeting')),
            ],
            options={
                'unique_together': {('available_at', 'meeting')},
            },
        ),
        migrations.CreateModel(
            name='ReservedMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('guest_fullname', models.CharField(max_length=256, verbose_name='Guest fullname')),
                ('guest_email', models.EmailField(max_length=254, verbose_name='Guest email')),
                ('meeting_schedule', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reserved', to='meetings.meetingschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
